
server:
  port: 8082
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: doctor-service
          uri: http://localhost:8080/
          predicates:
            - Path=/doctors/**
        - id: patient-service
          uri: http://localhost:8081/
          predicates:
            - Path=/patients/**

